### ISSUE TITLE
[General] Atlantic icons don't apply

### ISSUE THREAD

**Issue by simoselis** [joshuah345/iOSThemes#1]
[https://imgur.com/a/1ujn8kS](url)

Sorry for the spam, I wrote you an email and posted about it on reddit, the package description on Twickd sent me here.

Just some icons (like Waze, Pinterest..) apply successfully on Snowboard. Alternative icons show blank, and that's for all 3 versions (Light, Dark, Glyphs)
I had the free Atlantic (Dark) theme on Packix before, uninstalled it before even buying the final release.
What I did for now:

- Reinstalled the package
- Uicache
- Forced Update and Cleared Alternative Icons
- Reinstalled Snowboard
- Downgraded a few version of Snowboard

I'm on an iPhone 7 (GSM) running iOS 13.2.2 (last Checkra1n), with Atlantic 1.0 and Snowboard 1.2.74~Beta1

**Comment by joshuah345** [comment]
will be fixed in 1.0.1
snowboard bugs out at 512x512 px icon sizes
